"""
build.py
========
no_com/ 폴더의 앱을 PyInstaller onefile EXE 로 빌드하는 스크립트.

사용법
------
  python build.py                  # 이름 입력 프롬프트
  python build.py MyApp            # MyApp.exe
  python build.py 견적자동화       # 견적자동화.exe
  python build.py MyApp icon.ico   # 아이콘 포함

결과물
------
  no_com/dist/<앱이름>.exe   ← 단일 실행 파일
"""

import os
import sys
import textwrap
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))


# ── 인자 처리 ──────────────────────────────────────────────────

def _get_args():
    args = sys.argv[1:]
    if args:
        app_name = args[0].strip()
        icon     = args[1].strip() if len(args) >= 2 else ""
    else:
        app_name = input("프로세스명(EXE 파일명, 예: 견적자동화): ").strip()
        icon     = input("아이콘 경로 (없으면 엔터): ").strip()

    if not app_name:
        print("오류: 이름을 입력하세요.")
        sys.exit(1)

    if icon and not os.path.isabs(icon):
        icon = os.path.join(HERE, icon)

    if icon and not os.path.exists(icon):
        print(f"경고: 아이콘 파일을 찾을 수 없습니다 — {icon}")
        icon = ""

    return app_name, icon


# ── .spec 파일 생성 ────────────────────────────────────────────

def _make_spec(app_name: str, icon: str) -> str:
    icon_line = f'icon=r"{icon}",' if icon else ""

    spec = textwrap.dedent(f"""\
        # auto-generated by build.py — do not edit manually
        from pathlib import Path
        from PyInstaller.utils.hooks import collect_all

        HERE = Path(r"{HERE}")

        openpyxl_d, openpyxl_b, openpyxl_h = collect_all("openpyxl")
        fitz_d,     fitz_b,     fitz_h     = collect_all("fitz")

        a = Analysis(
            [str(HERE / "main.py")],
            pathex=[str(HERE)],
            binaries=[
                *openpyxl_b,
                *fitz_b,
            ],
            datas=[
                *openpyxl_d,
                *fitz_d,
            ],
            hiddenimports=[
                "PySide6.QtCore",
                "PySide6.QtGui",
                "PySide6.QtWidgets",
                "openpyxl.cell._writer",
                *openpyxl_h,
                *fitz_h,
                "pythoncom",
                "pywintypes",
                "win32api",
                "win32com",
                "win32com.client",
                "win32com.server",
                "win32con",
            ],
            hookspath=[],
            runtime_hooks=[],
            excludes=[],
            noarchive=False,
            optimize=1,
        )

        pyz = PYZ(a.pure)

        # ── onefile: a.binaries / a.datas 를 EXE 에 직접 포함, COLLECT 없음 ──
        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.datas,
            name="{app_name}",
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=False,
            {icon_line}
        )
    """)
    return spec


# ── 빌드 실행 ──────────────────────────────────────────────────

def main():
    app_name, icon = _get_args()

    spec_content = _make_spec(app_name, icon)

    # 임시 .spec 파일에 저장
    spec_path = os.path.join(HERE, f"_build_{app_name}.spec")
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)

    dist_dir = os.path.join(HERE, "dist")
    work_dir = os.path.join(HERE, "build")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        spec_path,
        "--distpath", dist_dir,
        "--workpath", work_dir,
        "--noconfirm",
        "--clean",
    ]

    print(f"\n{'='*50}")
    print(f"  앱 이름  : {app_name}")
    print(f"  아이콘   : {icon or '없음'}")
    print(f"  출력     : {os.path.join(dist_dir, app_name + '.exe')}")
    print(f"{'='*50}\n")

    result = subprocess.run(cmd, cwd=HERE)

    # 임시 spec 정리
    try:
        os.remove(spec_path)
    except OSError:
        pass

    if result.returncode == 0:
        out = os.path.join(dist_dir, f"{app_name}.exe")
        size_mb = os.path.getsize(out) / 1024 / 1024 if os.path.exists(out) else 0
        print(f"\n빌드 성공: {out}  ({size_mb:.1f} MB)")
    else:
        print(f"\n빌드 실패 (exit code={result.returncode})")

    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
