"""
build_onedir.py
===============
no_com/ 앱을 onedir 형태로 빌드하는 스크립트.
Python 미설치 환경에서도 동작 (Python 인터프리터 포함).

사용법
------
  python build_onedir.py                # 이름 프롬프트
  python build_onedir.py 견적자동화     # → dist/견적자동화/견적자동화.exe
  python build_onedir.py 견적자동화 icon.ico

배포 방법
---------
  dist/견적자동화/ 폴더 전체를 압축해서 전달
  수령자는 압축 해제 후 견적자동화.exe 실행
"""

import math
import os
import sys
import textwrap
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))


def _get_args():
    args = sys.argv[1:]
    if args:
        app_name = args[0].strip()
        icon     = args[1].strip() if len(args) >= 2 else ""
    else:
        app_name = input("프로세스명(EXE 파일명, 예: 견적자동화): ").strip()
        icon     = input("아이콘 경로 (없으면 엔터): ").strip()

    if not app_name:
        print("오류: 이름을 입력하세요.")
        sys.exit(1)

    if icon and not os.path.isabs(icon):
        icon = os.path.join(HERE, icon)
    if icon and not os.path.exists(icon):
        print(f"경고: 아이콘 파일 없음 — {icon}")
        icon = ""

    return app_name, icon


def _make_spec(app_name: str, icon: str) -> str:
    icon_line = f'icon=r"{icon}",' if icon else ""
    return textwrap.dedent(f"""\
        # auto-generated by build_onedir.py — do not edit manually
        import glob, site
        from pathlib import Path
        from PyInstaller.utils.hooks import collect_all

        HERE = Path(r"{HERE}")

        openpyxl_d, openpyxl_b, openpyxl_h = collect_all("openpyxl")
        fitz_d,     fitz_b,     fitz_h     = collect_all("fitz")
        pil_d,      pil_b,      pil_h      = collect_all("PIL")
        wdm_d,      wdm_b,      wdm_h      = collect_all("webdriver_manager")

        # pythoncom / pywintypes DLL 직접 수집 (ordinal 오류 방지)
        _pywin32_dlls = []
        for _sp_dir in site.getsitepackages():
            _pywin32_dlls += [
                (f, ".")
                for f in glob.glob(str(Path(_sp_dir) / "pywin32_system32" / "*.dll"))
            ]

        a = Analysis(
            [str(HERE / "main.py")],
            pathex=[str(HERE)],
            binaries=[
                *openpyxl_b,
                *fitz_b,
                *pil_b,
                *wdm_b,
                *_pywin32_dlls,
            ],
            datas=[
                *openpyxl_d,
                *fitz_d,
                *pil_d,
                *wdm_d,
            ],
            hiddenimports=[
                # 앱 모듈 (importlib.import_module 동적 로딩 → PyInstaller 자동 감지 불가)
                "pages",
                "page_common",
                "page_quote",
                "page_esign",
                "page_rack",
                "excel_io",
                "core",
                "widgets",
                "approval_auto",
                "PySide6.QtCore",
                "PySide6.QtGui",
                "PySide6.QtWidgets",
                "PySide6.QtSvg",
                "PySide6.QtPrintSupport",
                "openpyxl.cell._writer",
                *openpyxl_h,
                *fitz_h,
                *pil_h,
                *wdm_h,
                # PIL.*는 pil_h에 이미 포함되어 있으나 명시적으로 추가 (누락 방지)
                "PIL.ImageGrab",
                # pyautogui: approval_auto.py 에서 Tab/Enter 키 입력에 직접 사용
                "pyautogui",
                "pyautogui._pyautogui_win",   # Windows 백엔드만 포함
                "pythoncom",
                "pywintypes",
                "win32api",
                "win32com",
                "win32com.client",
                # win32com.server: 앱이 COM 서버 기능을 사용하지 않으므로 제외
                "win32con",
                "win32timezone",
                "tarfile",  # pymupdf 동적 임포트 (정적 분석 불가)
                # selenium: 함수 내 lazy import라 정적 분석이 놓칠 수 있는 submodule 명시
                "selenium",
                "selenium.webdriver",
                "selenium.webdriver.chrome",
                "selenium.webdriver.chrome.webdriver",
                "selenium.webdriver.chrome.service",
                "selenium.webdriver.chrome.options",
                "selenium.webdriver.remote.webdriver",
                "selenium.webdriver.remote.remote_connection",
                "selenium.webdriver.remote.errorhandler",
                "selenium.webdriver.remote.command",
                "selenium.webdriver.common.by",
                "selenium.webdriver.common.service",
                "selenium.webdriver.common.keys",
                "selenium.webdriver.support.ui",
                "selenium.webdriver.support.expected_conditions",
                "webdriver_manager",
                "webdriver_manager.chrome",
            ],
            hookspath=[],
            runtime_hooks=[],
            excludes=[
                # UI 툴킷
                "tkinter",
                # 과학 계산 (앱 미사용)
                "matplotlib", "numpy", "scipy",
                # 테스트/디버그 도구
                "unittest", "doctest", "pdb", "profile", "cProfile",
                # 미사용 stdlib (pkg_resources/win32com 체인에 영향 없는 것만 제외)
                "difflib", "pickletools",
                "xmlrpc", "pydoc", "idlelib",
                "ensurepip", "venv",
                "curses",
                "cgi", "cgitb",
                "msilib",
                # 미사용 네트워크 프로토콜
                "ftplib", "imaplib", "smtplib", "poplib", "nntplib", "telnetlib",
                # 멀티프로세싱 (앱은 QThread 사용)
                "multiprocessing.pool",
                # numba: 앱 미사용, tbb12.dll 미존재 시 COLLECT 단계 오류 유발
                "numba",
                # pyautogui Linux/Mac 백엔드: Windows 빌드에 불필요, SyntaxWarning 원인
                "pyautogui._pyautogui_x11",
                "pyautogui._pyautogui_osx",
                # ※ distutils, lib2to3, sqlite3, dbm 은 제외하지 않음:
                #   win32com → pkg_resources → distutils/lib2to3 의존 체인이 존재해
                #   제외 시 빌드 또는 런타임 오류 발생 가능
            ],
            noarchive=False,  # .pyc를 PYZ 아카이브로 압축 → 첫 실행 시 Defender 스캔 파일 수 최소화
            optimize=2,       # 2: docstring 제거 → .pyc 크기 감소, 임포트 속도 향상
        )

        pyz = PYZ(a.pure)

        exe = EXE(
            pyz,
            a.scripts,
            [],
            exclude_binaries=True,
            name="{app_name}",
            debug=False,
            strip=False,
            upx=False,
            console=False,
            {icon_line}
        )

        coll = COLLECT(
            exe,
            a.binaries,
            a.datas,
            strip=False,
            upx=True,
            upx_exclude=[
                # Qt DLL: UPX 압축 시 리소스 섹션 손상 위험
                "Qt6Core.dll", "Qt6Gui.dll", "Qt6Widgets.dll",
                "Qt6Network.dll", "Qt6PrintSupport.dll", "Qt6Svg.dll",
                "Qt6OpenGL.dll", "Qt6XcbQpa.dll", "Qt6DBus.dll",
                # MSVC 런타임
                "vcruntime140.dll", "vcruntime140_1.dll",
                "MSVCP140.dll", "MSVCP140_1.dll",
                # pywin32: ordinal-export DLL — UPX가 export table 손상 가능 → COM 오류
                "pythoncom*.dll", "pywintypes*.dll",
                # Python C 확장(.pyd): UPX 압축 시 임포트 실패 가능
                "*.pyd",
            ],
            name="{app_name}",
        )
    """)


def _create_icon() -> str:
    """PIL로 견적·전자서명 앱에 어울리는 아이콘을 코드로 생성해 icon.ico 경로를 반환한다."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("경고: Pillow 미설치 — 아이콘 없이 빌드합니다.")
        return ""
    except Exception as e:
        print(f"경고: Pillow 초기화 오류 ({e}) — 아이콘 없이 빌드합니다.")
        return ""

    out_path = os.path.join(HERE, "icon.ico")
    sizes = [256, 128, 64, 48, 32, 24, 16]
    images = []

    for sz in sizes:
        img = Image.new("RGBA", (sz, sz), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)

        # ── 배경: 파란 둥근 사각형 ──────────────────────────────
        BG  = (21, 101, 192, 255)   # #1565C0
        PAD = max(1, sz // 16)
        R   = max(2, sz // 8)
        try:
            # rounded_rectangle: Pillow 8.2.0+
            draw.rounded_rectangle([PAD, PAD, sz - PAD - 1, sz - PAD - 1],
                                   radius=R, fill=BG)
        except AttributeError:
            draw.rectangle([PAD, PAD, sz - PAD - 1, sz - PAD - 1], fill=BG)

        # ── 문서 몸체 (흰색 사각형, 우상단 모서리 접힘) ──────────
        DX   = sz * 0.20
        DY   = sz * 0.14
        DW   = sz * 0.60
        DH   = sz * 0.72
        FOLD = sz * 0.15          # 접힌 삼각형 크기
        DOC  = (255, 255, 255, 255)
        # 접힘 다각형: 우상단 모서리 제외 5꼭짓점
        poly = [
            (DX,          DY),
            (DX + DW - FOLD, DY),
            (DX + DW,    DY + FOLD),
            (DX + DW,    DY + DH),
            (DX,          DY + DH),
        ]
        draw.polygon(poly, fill=DOC)

        # 접힘 삼각형 음영 (연한 회색)
        SHADOW = (200, 210, 230, 255)
        fold_tri = [
            (DX + DW - FOLD, DY),
            (DX + DW,        DY + FOLD),
            (DX + DW - FOLD, DY + FOLD),
        ]
        draw.polygon(fold_tri, fill=SHADOW)

        # ── 문서 안 텍스트 줄 (파란 가로선) ─────────────────────
        LINE_CLR = (21, 101, 192, 200)
        lx0  = DX + sz * 0.07
        lx1  = DX + DW - sz * 0.07
        ly   = DY + FOLD + sz * 0.07
        step = sz * 0.10
        lw   = max(1, sz // 48)
        for i in range(4):
            y = ly + i * step
            # 마지막 줄 오른쪽은 짧게 (줄 끝 느낌)
            rx = lx1 if i < 3 else lx0 + (lx1 - lx0) * 0.55
            draw.rectangle([lx0, y, rx, y + lw], fill=LINE_CLR)

        # ── 서명 곡선 (사인파 형태) ──────────────────────────────
        SIG  = (255, 193, 7, 255)   # 노란빛 금색
        SX   = DX + sz * 0.07
        SEW  = DX + DW - sz * 0.09
        SY   = DY + DH - sz * 0.14
        AMP  = sz * 0.04
        slw  = max(1, sz // 32)
        pts  = []
        steps = max(20, sz // 4)
        for s in range(steps + 1):
            t = s / steps
            x = SX + t * (SEW - SX)
            y = SY + math.sin(t * math.pi * 3) * AMP
            pts.append((x, y))
        for i in range(len(pts) - 1):
            x0, y0 = pts[i]
            x1, y1 = pts[i + 1]
            draw.line([x0, y0, x1, y1], fill=SIG, width=slw)

        images.append(img)

    images[0].save(out_path, format="ICO", append_images=images[1:],
                   sizes=[(s, s) for s in sizes])
    print(f"  아이콘 생성 : {out_path}")
    return out_path


def main():
    app_name, icon = _get_args()

    if not icon:
        icon = _create_icon()

    spec_path = os.path.join(HERE, f"_build_{app_name}.spec")
    dist_dir  = os.path.join(HERE, "dist")
    work_dir  = os.path.join(HERE, "build")

    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(_make_spec(app_name, icon))

    log_path = os.path.join(HERE, f"_build_{app_name}.log")
    cmd = [
        sys.executable, "-m", "PyInstaller",
        spec_path,
        "--distpath", dist_dir,
        "--workpath", work_dir,
        "--noconfirm",
        "--clean",
    ]

    print(f"\n{'='*54}")
    print(f"  앱 이름 : {app_name}")
    print(f"  아이콘  : {icon or '없음'}")
    print(f"  출력    : {os.path.join(dist_dir, app_name)}/")
    print(f"  로그    : {log_path}")
    print(f"{'='*54}")
    print("  빌드 진행 중 (수 분 소요)...\n")

    # 콘솔 실시간 출력 + 로그 파일 동시 저장 (tee)
    returncode = 1
    try:
        proc = subprocess.Popen(
            cmd, cwd=HERE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace",
        )
        with open(log_path, "w", encoding="utf-8") as log_f:
            for line in proc.stdout:
                sys.stdout.write(line)
                sys.stdout.flush()
                log_f.write(line)
        proc.wait()
        returncode = proc.returncode
    except Exception as e:
        print(f"\n빌드 실행 오류: {e}")

    try:
        os.remove(spec_path)
    except OSError:
        pass

    if returncode == 0:
        out_dir = os.path.join(dist_dir, app_name)
        exe     = os.path.join(out_dir, f"{app_name}.exe")
        size_mb = sum(
            os.path.getsize(os.path.join(r, f))
            for r, _, fs in os.walk(out_dir) for f in fs
        ) / 1024 / 1024
        print(f"\n{'='*54}")
        print(f"  완료  : {exe}")
        print(f"  크기  : {size_mb:.1f} MB (폴더 전체)")
        print()
        print(f"  배포  : dist/{app_name}/ 폴더 전체를 압축해서 전달")
        print(f"  실행  : {app_name}.exe 더블클릭 (Python 불필요)")
        print(f"  인가  : {app_name}.exe 단일 파일 해시 제출")
        print(f"{'='*54}\n")
    else:
        print(f"\n빌드 실패 (exit code={returncode})")
        print(f"  오류 로그: {log_path}")
        print(f"  로그 파일을 열어 ERROR / CRITICAL 메시지를 확인하세요.")

    sys.exit(returncode)


if __name__ == "__main__":
    main()
