"""
build_onedir.py
===============
no_com/ 앱을 onedir 형태로 빌드하는 스크립트.
Python 미설치 환경에서도 동작 (Python 인터프리터 포함).

사용법
------
  python build_onedir.py                # 이름 프롬프트
  python build_onedir.py 견적자동화     # → dist/견적자동화/견적자동화.exe
  python build_onedir.py 견적자동화 icon.ico

배포 방법
---------
  dist/견적자동화/ 폴더 전체를 압축해서 전달
  수령자는 압축 해제 후 견적자동화.exe 실행
"""

import os
import sys
import textwrap
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))


def _get_args():
    args = sys.argv[1:]
    if args:
        app_name = args[0].strip()
        icon     = args[1].strip() if len(args) >= 2 else ""
    else:
        app_name = input("프로세스명(EXE 파일명, 예: 견적자동화): ").strip()
        icon     = input("아이콘 경로 (없으면 엔터): ").strip()

    if not app_name:
        print("오류: 이름을 입력하세요.")
        sys.exit(1)

    if icon and not os.path.isabs(icon):
        icon = os.path.join(HERE, icon)
    if icon and not os.path.exists(icon):
        print(f"경고: 아이콘 파일 없음 — {icon}")
        icon = ""

    return app_name, icon


def _make_spec(app_name: str, icon: str) -> str:
    icon_line = f'icon=r"{icon}",' if icon else ""
    return textwrap.dedent(f"""\
        # auto-generated by build_onedir.py — do not edit manually
        import glob, site
        from pathlib import Path
        from PyInstaller.utils.hooks import collect_all

        HERE = Path(r"{HERE}")

        openpyxl_d, openpyxl_b, openpyxl_h = collect_all("openpyxl")
        fitz_d,     fitz_b,     fitz_h     = collect_all("fitz")
        pil_d,      pil_b,      pil_h      = collect_all("PIL")

        # pythoncom / pywintypes DLL 직접 수집 (ordinal 오류 방지)
        _pywin32_dlls = []
        for _sp_dir in site.getsitepackages():
            _pywin32_dlls += [
                (f, ".")
                for f in glob.glob(str(Path(_sp_dir) / "pywin32_system32" / "*.dll"))
            ]

        a = Analysis(
            [str(HERE / "main.py")],
            pathex=[str(HERE)],
            binaries=[
                *openpyxl_b,
                *fitz_b,
                *pil_b,
                *_pywin32_dlls,
            ],
            datas=[
                *openpyxl_d,
                *fitz_d,
                *pil_d,
            ],
            hiddenimports=[
                # 앱 모듈 (importlib.import_module 동적 로딩 → PyInstaller 자동 감지 불가)
                "pages",
                "excel_io",
                "core",
                "widgets",
                "approval_auto",
                "PySide6.QtCore",
                "PySide6.QtGui",
                "PySide6.QtWidgets",
                "PySide6.QtSvg",
                "PySide6.QtPrintSupport",
                "openpyxl.cell._writer",
                *openpyxl_h,
                *fitz_h,
                *pil_h,
                "PIL",
                "PIL.ImageGrab",
                "PIL.Image",
                "pythoncom",
                "pywintypes",
                "win32api",
                "win32com",
                "win32com.client",
                "win32com.server",
                "win32con",
                "win32timezone",
                "selenium",
                "selenium.webdriver",
                "selenium.webdriver.chrome",
                "selenium.webdriver.chrome.service",
                "selenium.webdriver.chrome.options",
                "selenium.webdriver.common.by",
                "selenium.webdriver.support.ui",
                "selenium.webdriver.support.expected_conditions",
                "selenium.webdriver.common.keys",
                "webdriver_manager",
                "webdriver_manager.chrome",
            ],
            hookspath=[],
            runtime_hooks=[],
            excludes=["tkinter", "matplotlib", "numpy", "scipy"],
            noarchive=False,
            optimize=1,
        )

        pyz = PYZ(a.pure)

        exe = EXE(
            pyz,
            a.scripts,
            [],
            exclude_binaries=True,
            name="{app_name}",
            debug=False,
            strip=False,
            upx=False,
            console=False,
            {icon_line}
        )

        coll = COLLECT(
            exe,
            a.binaries,
            a.datas,
            strip=False,
            upx=True,
            upx_exclude=[],
            name="{app_name}",
        )
    """)


def main():
    app_name, icon = _get_args()

    spec_path = os.path.join(HERE, f"_build_{app_name}.spec")
    dist_dir  = os.path.join(HERE, "dist")
    work_dir  = os.path.join(HERE, "build")

    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(_make_spec(app_name, icon))

    cmd = [
        sys.executable, "-m", "PyInstaller",
        spec_path,
        "--distpath", dist_dir,
        "--workpath", work_dir,
        "--noconfirm",
        "--clean",
    ]

    print(f"\n{'='*54}")
    print(f"  앱 이름 : {app_name}")
    print(f"  아이콘  : {icon or '없음'}")
    print(f"  출력    : {os.path.join(dist_dir, app_name)}/")
    print(f"{'='*54}\n")

    result = subprocess.run(cmd, cwd=HERE)

    try:
        os.remove(spec_path)
    except OSError:
        pass

    if result.returncode == 0:
        out_dir = os.path.join(dist_dir, app_name)
        exe     = os.path.join(out_dir, f"{app_name}.exe")
        size_mb = sum(
            os.path.getsize(os.path.join(r, f))
            for r, _, fs in os.walk(out_dir) for f in fs
        ) / 1024 / 1024
        print(f"\n{'='*54}")
        print(f"  완료  : {exe}")
        print(f"  크기  : {size_mb:.1f} MB (폴더 전체)")
        print()
        print(f"  배포  : dist/{app_name}/ 폴더 전체를 압축해서 전달")
        print(f"  실행  : {app_name}.exe 더블클릭 (Python 불필요)")
        print(f"  인가  : {app_name}.exe 단일 파일 해시 제출")
        print(f"{'='*54}\n")
    else:
        print(f"\n빌드 실패 (exit code={result.returncode})")

    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
